### ISSUE TITLE
类型不匹配导致无法开始游戏

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-game-hsyhhssyy-duel#2]
choice.user_id 为int型
duel_victim 为 string型
导致 choice.user_id == duel_victim 判断值始终为false

**Comment by wutongshufqw** [comment]
以下是我的测试
```python
            print(type(choice.user_id))
            print(type(duel_victim))
            print(choice.user_id == duel_victim)
```
这是它的输出结果
<class 'int'>
<class 'str'>
False

**Comment by wutongshufqw** [comment]
将if choice.user_id != duel_victim:
替换为
if str(choice.user_id) != duel_victim:
即可

**Comment by wutongshufqw** [comment]
希望作者大大能尽快修复qwq

**Comment by hsyhhssyy** [comment]
更新了，替换了所有对choice.user_id的调用，并且强制设置了两个变量的类型，你可以再试试。

**Comment by hsyhhssyy** [comment]
话说为什么不提一个pr呢（

**Comment by wutongshufqw** [comment]
> 

怕我自己改坏了QWQ
